version: '3.9'

services:
  postgres:
    image: library/postgres:14-bullseye
    container_name: postgres-app
    restart: on-failure
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 3s
      retries: 30
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  pg_admin:
    container_name: pgadmin4-app
    image: dpage/pgadmin4
    restart: on-failure
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    ports:
      - "5050:80"

  app:
    container_name: petowo-app
    restart: on-failure
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      - APP_PORT
    build:
        context: .
        dockerfile: Dockerfile
    command: ["/app/docker/app.sh"]
    depends_on:
        postgres:
          condition: service_healthy
    volumes:
      - migrations-data:/app/migrations/versions
    ports:
      - "${APP_PORT}:${APP_PORT}"

volumes:
  db-data:
  migrations-data:
